Prog6/Controllers/HotelkamersController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.Composition;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Domain;
using Prog6.Kamers;
using Prog6.Models;
using Prog6.Respositories.Interfaces;

namespace Prog6.Controllers
{
    public class HotelkamersController : Controller
    {
        private IHotelkamerRepository _hotelkamerRepository;

        public HotelkamersController(IHotelkamerRepository hotelkamerRepository)
        {
            _hotelkamerRepository = hotelkamerRepository;
        }
        // GET: Hotelkamers
        public ActionResult Index()
        {
            return View(_hotelkamerRepository.GetAll());
        }

        // GET: Hotelkamers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HotelkamerModel hotelkamer = _hotelkamerRepository.Get(id.Value);
            if (hotelkamer == null)
            {
                return HttpNotFound();
            }
            return View(hotelkamer);
        }

        // GET: Hotelkamers/Create
        public ActionResult Create()
        {
            int[] Groote = new[] {2, 3, 5 };
            ViewBag.Groote = new SelectList(Groote);
            ViewBag.Type = new SelectList(Kamer.GetKamers(), "Name", "Description");
            return View();
        }

        // POST: Hotelkamers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[Bind(Include = "Id,Groote,Type")] Hotelkamer hotelkamer
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(HotelkamerModel hotelkamer)
        {
            if (ModelState.IsValid)
            {
                _hotelkamerRepository.Create(hotelkamer);
                _hotelkamerRepository.Save();
                return RedirectToAction("Index");
            }

            ViewBag.Type = new SelectList(Kamer.GetKamers(), "Name", "Description", hotelkamer.Type);

            return View(hotelkamer);
        }

        // GET: Hotelkamers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HotelkamerModel hotelkamer = _hotelkamerRepository.Get(id.Value);
            if (hotelkamer == null)
            {
                return HttpNotFound();
            }
            ViewBag.Type = new SelectList(Kamer.GetKamers(), "Name", "Description", hotelkamer.Type);
            ViewBag.Groote = new SelectList(new int[] {2, 3, 5}, hotelkamer.Groote);
            return View(hotelkamer);
        }

        // POST: Hotelkamers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[Bind(Include = "Id,Groote,Type")] Hotelkamer hotelkamer
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(HotelkamerModel hotelkamer)
        {
            if (ModelState.IsValid)
            {
                _hotelkamerRepository.Update(hotelkamer);
                _hotelkamerRepository.Save();
                return RedirectToAction("Index");
            }
            ViewBag.Type = new SelectList(Kamer.GetKamers(), "Name", "Description", hotelkamer.Type);
            return View(hotelkamer);
        }

        // GET: Hotelkamers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (TempData["Error"] != null)
            {
                ViewBag.Error = TempData["Error"].ToString();
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HotelkamerModel hotelkamer = _hotelkamerRepository.Get(id.Value);
            if (hotelkamer == null)
            {
                return HttpNotFound();
            }
            return View(hotelkamer);
        }

        // POST: Hotelkamers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            HotelkamerModel hotelkamer = _hotelkamerRepository.Get(id);
            if (hotelkamer.Tamagotchis.Count == 0)
            {
                _hotelkamerRepository.Delete(hotelkamer);
                _hotelkamerRepository.Save();
                return RedirectToAction("Index");
            }
            else
            {
                TempData["Error"] = "Er is nog een openstaande boeking voor deze hotelkamer.";
                return RedirectToAction("Delete", new {id = hotelkamer.Id});
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                //db.GetContext().Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Prog6/Controllers/TamagotchisController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.Composition;
using System.Data;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Domain;
using Ninject;
using Prog6.Models;
using Prog6.Respositories.Interfaces;

namespace Prog6.Controllers
{
    public class TamagotchisController : Controller
    {
        private ITamagotchiRepository _tamagotchiRepository;

        [Inject]
        public TamagotchisController(ITamagotchiRepository tamagotchiRepository)
        {
            _tamagotchiRepository = tamagotchiRepository;
        }

        // GET: Tamagotchis
        public ActionResult Index()
        {
            return View(_tamagotchiRepository.GetAll());
        }

        // GET: Tamagotchis/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TamagotchiModel tamagotchi = _tamagotchiRepository.Get(id.Value);

            if (tamagotchi == null)
            {
                return HttpNotFound();
            }
            return View(tamagotchi);
        }

        // GET: Tamagotchis/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Tamagotchis/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        // [Bind(Include = "Id,Naam,Leeftijd,Centjes,Level,Gezondheid,Verveling,Levend")] Tamagotchi tamagotchi
        public ActionResult Create(TamagotchiModel tamagotchi)
        {
            if (ModelState.IsValid)
            {
                tamagotchi.Leeftijd = 0;
                tamagotchi.Centjes = 100;
                tamagotchi.Level = 0;
                tamagotchi.Gezondheid = 100;
                tamagotchi.Verveling = 0;
                tamagotchi.Levend = 1;
                _tamagotchiRepository.Create(tamagotchi);
                _tamagotchiRepository.Save();
                return RedirectToAction("Index");
            }

            return View(tamagotchi);
        }

        // GET: Tamagotchis/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TamagotchiModel tamagotchi = _tamagotchiRepository.Get(id.Value);
            if (tamagotchi == null)
            {
                return HttpNotFound();
            }
            return View(tamagotchi);
        }

        // POST: Tamagotchis/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        // [Bind(Include = "Id,Naam,Leeftijd,Centjes,Level,Gezondheid,Verveling,Levend")] Tamagotchi tamagotchi
        public ActionResult Edit(TamagotchiModel tamagotchi)
        {
            if (ModelState.IsValid)
            {
                //Tamagotchi t1 = db.GetContext().Tamagotchis.Where(t => t.Id == tamagotchi.Id).FirstOrDefault();
                //t1.Naam = tamagotchi.Naam;
                _tamagotchiRepository.Update(tamagotchi);
                _tamagotchiRepository.Save();
                return RedirectToAction("Index");
            }
            return View(tamagotchi);
        }

        // GET: Tamagotchis/Delete/5
        public ActionResult Delete(int? id)
        {
            if (TempData["Error"] != null)
            {
                ViewBag.Error = TempData["Error"].ToString();
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TamagotchiModel tamagotchi = _tamagotchiRepository.Get(id.Value);
            if (tamagotchi == null)
            {
                return HttpNotFound();
            }
            return View(tamagotchi);
        }

        // POST: Tamagotchis/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TamagotchiModel tamagotchi = _tamagotchiRepository.Get(id);
            if (tamagotchi.HotelKamers.Count == 0)
            {
                _tamagotchiRepository.Delete(tamagotchi);
                _tamagotchiRepository.Save();
            }
            else
            {
                TempData["Error"] = "Er is nog een openstaande boeking voor deze tamagotchi.";
                return RedirectToAction("Delete", new { id = tamagotchi.Id });
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            /*if (disposing)
            {
                //db.GetContext().Dispose();
            }
            base.Dispose(disposing);*/
        }
    }
}

Prog6/Views/Hotelkamers/Create.cshtml
@model Prog6.Models.HotelkamerModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Hotelkamer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Groote, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Groote", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Groote, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, "Type", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Type", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Prog6/Views/Hotelkamers/Delete.cshtml
@model Prog6.Models.HotelkamerModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

@if (ViewBag.Error != null)
{
    <div class="alert alert-danger">
        <strong>Error: </strong>@ViewBag.Error
    </div>
}


<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Hotelkamer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Groote)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Groote)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Prog6/Views/Hotelkamers/Details.cshtml
@model Prog6.Models.HotelkamerModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Hotelkamer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Groote)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Groote)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Prog6/Views/Hotelkamers/Edit.cshtml
@model Prog6.Models.HotelkamerModel

@{
    ViewBag.Title = "Edit";
}
<!-- id, groote, type-->
<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Hotelkamer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Groote, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Groote", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Groote, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, "Type", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Type", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Prog6/Views/Hotelkamers/Index.cshtml
@model IEnumerable<Prog6.Models.HotelkamerModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Groote)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Type)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Groote)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Type)
        </td>
        <td>
            @Html.ActionLink("Kamer boeken", "Tamagotchis", "Boeking", new { id = item.Id }, new {@class = "btn btn-primary"})
            @Html.ActionLink("Edit", "Edit", new {id = item.Id}) |
            @Html.ActionLink("Details", "Details", new {id = item.Id}) |
            @Html.ActionLink("Delete", "Delete", new {id = item.Id})
        </td>
    </tr>
}

</table>