Prog6/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.Composition;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain;
using Prog6.Respositories.Interfaces;
using Prog6.Models;

namespace Prog6.Controllers
{
    public class HomeController : Controller
    {
        private ITamagotchiRepository _tamagotchiRepository;
        private IHotelkamerRepository _hotelkamerRepository;

        public HomeController(ITamagotchiRepository tamagotchiRepository, IHotelkamerRepository hotelkamerRepository)
        {
            _tamagotchiRepository = tamagotchiRepository;
            _hotelkamerRepository = hotelkamerRepository;
        }        

        public ActionResult Index()
        {
            List<TamagotchiModel> AllTamagotchis = _tamagotchiRepository.GetAll();
            List<TamagotchiModel> AliveTamagotchis = AllTamagotchis.Where(t => t.Levend == 1).ToList();
            List<TamagotchiModel> DeadTamagotchis = AllTamagotchis.Where(t => t.Levend == 0).ToList();
            List<TamagotchiModel> RoomlessTamagotchis = new List<TamagotchiModel>(AliveTamagotchis);
            _hotelkamerRepository.GetAll().Where(t => t.Tamagotchis.Count > 0).ToList().ForEach((h) =>
            {
                foreach (var objTamagotchi in h.Tamagotchis)
                {
                    for (int i = 0; i < RoomlessTamagotchis.Count; i++)
                    {
                        if (RoomlessTamagotchis[i].Id == objTamagotchi.Id)
                        {
                            RoomlessTamagotchis.Remove(RoomlessTamagotchis[i]);
                            i--;
                        }
                    }
                }
            });

            if (TempData["NachtComplete"] != null)
                ViewBag.NachtComplete = TempData["NachtComplete"];

            return View(new HomeIndexModel()
            {
                AllTamagotchis = AllTamagotchis,
                AliveTamagotchis = AliveTamagotchis,
                DeadTamagotchis =  DeadTamagotchis,
                RoomlessTamagotchis = RoomlessTamagotchis
            });
        }
    }
}

Prog6/Controllers/NachtController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Prog6.Kamers;
using Prog6.Models;
using Prog6.Respositories.Interfaces;

namespace Prog6.Controllers
{
    public class NachtController : Controller
    {
        private IHotelkamerRepository _hotelkamerRepository;
        private IBoekingRepository _boekingRepository;
        private ITamagotchiRepository _tamagotchiRepository;

        public NachtController(IHotelkamerRepository hotelkamerRepository, IBoekingRepository boekingRepository, ITamagotchiRepository tamagotchiRepository)
        {
            _hotelkamerRepository = hotelkamerRepository;
            _boekingRepository = boekingRepository;
            _tamagotchiRepository = tamagotchiRepository;
        }

        // GET: Nacht
        public ActionResult Index()
        {
            List<TamagotchiModel> RoomlessTamagotchis = _tamagotchiRepository.GetAllAlive();
            _hotelkamerRepository.GetAll().Where(t => t.Tamagotchis.Count > 0).ToList().ForEach((h) =>
            {
                foreach (var objTamagotchi in h.Tamagotchis)
                {
                    for (int i = 0; i < RoomlessTamagotchis.Count; i++)
                    {
                        if (RoomlessTamagotchis[i].Id == objTamagotchi.Id)
                        {
                            RoomlessTamagotchis.Remove(RoomlessTamagotchis[i]);
                            i--;
                        }
                    }
                }
            });

            RoomlessTamagotchis.ForEach((t) =>
            {
                t.Verveling += 20;
                t.Gezondheid -= 20;
                t.Leeftijd += 1;
                t.Level += 1;
                _tamagotchiRepository.Update(t);
            });
            _tamagotchiRepository.Save();

            _hotelkamerRepository.GetAll().Where(h => h.Tamagotchis.Count > 0).ToList().ForEach(k =>
            {
                IKamer kamer = Kamer.GetKamer(k.Type);
                kamer.Nacht(k.Tamagotchis.Select(t => new TamagotchiModel() {_tamagotchi = t}).ToList());
                _hotelkamerRepository.Update(k);
                _hotelkamerRepository.Save();
                k.Tamagotchis.Clear();
                _hotelkamerRepository.Update(k);
                _hotelkamerRepository.Save();
            });

            TempData["NachtComplete"] = "Er is een nieuwe dag aangebroken!";

            return RedirectToAction("Index", "Home");
        }
    }
}

Prog6/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Prog6/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Prog6/Views/Home/Index.cshtml
@model Prog6.Models.HomeIndexModel

@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Tamagotchi Hotel</h1>
    <p class="lead">Made by Bart Renders & Michat Morel</p>
</div>

<div class="row">
    @if (ViewBag.NachtComplete != null)
    {
        <div class="alert alert-success">
            @ViewBag.NachtComplete
        </div>
    }
    
    @Html.ActionLink("Nacht starten", "Index", "Nacht")

    <div class="col-md-6">
        <h2>Alive Tamagotchi's</h2>
        <table class="table">
            <tr>
                <th>Naam</th>
                <th>Level</th>
                <th>Centjes</th>
                <th>Gezondheid</th>
                <th>Levend</th>
            </tr>
            <!-- Overview of tamagotchi's that are alive -->
            @foreach (var item in Model.AliveTamagotchis)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Naam)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Level)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Centjes)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Gezondheid)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.Levend)
                    </td>
                </tr>
            }
        </table>
    </div>

    <div class="col-md-6">
        <!-- Overview of tamagotchi's that are dead -->
        <h2>Dead Tamagotchi's</h2>
        <table class="table">
            <tr>
                <th>Naam</th>
                <th>Level</th>
                <th>Centjes</th>
                <th>Gezondheid</th>
                <th>Levend</th>
            </tr>
            <!-- Overview of tamagotchi's that are alive -->
            @foreach (var item in Model.DeadTamagotchis)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Naam)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Level)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Centjes)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Gezondheid)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.Levend)
                    </td>
                </tr>
            }
        </table>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <!-- Overview of tamagotchi's without a room -->
        <h2>Roomless Tamagotchi's</h2>
        <table class="table">
            <tr>
                <th>Naam</th>
                <th>Level</th>
                <th>Centjes</th>
                <th>Gezondheid</th>
                <th></th>
            </tr>
            <!-- Overview of tamagotchi's that are alive -->
            @foreach (var item in Model.RoomlessTamagotchis)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Naam)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Level)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Centjes)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Gezondheid)
                    </td>

                    <td>
                        @Html.ActionLink("Kamer boeken", "Index", "Boeking", null, new {@class = "btn btn-primary"})
                    </td>
                </tr>
            }
        </table>
    </div>
</div>